const moduleAlias = require('module-alias')

moduleAlias.addAlias('@', __dirname + '/')
moduleAlias.addAlias('@type', __dirname + '/core/types')
moduleAlias.addAlias('@run', __dirname + '/core/run')
moduleAlias.addAlias('@controller', __dirname + '/core/controller')
moduleAlias.addAlias('@utils', __dirname + '/core/utils')
moduleAlias.addAlias('@config', __dirname + '/core/config')
moduleAlias.addAlias('@model', __dirname + '/core/model')
moduleAlias.addAlias('@ipc', __dirname + '/core/ipc')
moduleAlias.addAlias('@service', __dirname + '/core/service')
moduleAlias.addAlias('@net', __dirname + '/core/net')
moduleAlias.addAlias('@annotation', __dirname + '/core/annotation')
moduleAlias.addAlias('@interactive', __dirname + '/core/interactive')
moduleAlias.addAlias('@img', __dirname + '/view/assets/img')